authorName: default
experimentName: dkvmn
trialConcurrency: 4
maxExecDuration: 24h
maxTrialNum: 600
trainingServicePlatform: local
# 搜索空间文件
searchSpacePath: _search_space.json
useAnnotation: false
tuner:
  builtinTunerName: TPE
# 运行的命令，以及 Trial 代码的路径
trial:
  command: python3.6 run.py
  codeDir: .
  gpuNum: 1
